# main menu navigation
menu:
  Home: /
  About: /about
  Archive: /archives

widgets:
  - tag
  - archive
  - recent_posts
  - category
  - profile

# social config
social:
  zhihu: 
  twitter: 
  facebook: 
  linkedin:
  instagram: 
  github: 1PingSun
  telegram: sunyiping
  signal:

user:
  name: 1Ping
  avatar: img/avatar.webp
  location: Taiwan
  description: Persistent effort always pays off.
  footnotes: # footnote

# documents: https://github.com/utterance/utterances
# API config: https://utteranc.es/
comment_utteranc:
  enable: true
  repo: 1PingSun/1PingSun.github.io # your blog repo


# documents: https://valine.js.org/quickstart.html
comment_valine:
  enable: false
  appId:
  appKey:

comment_disqus:
    enable: false
    url:  # the url of your website main domain like this https://xxx.xxx/
    name: # the short name in disqus

# dark
# light
# user-can-set
appearance: auto # Default value is auto

# Miscellaneous
favicon: img/favicon.ico

# friend_links:
#   - title: Google
#     link: https://www.google.com/
#   - title: Github
#     link: https://www.github.com/
#   - title: V2EX
#     link: https://v2ex.com/
#   - title: Twitter
#     link: https://twitter.com/

# Google Analytics
ga_track_id: G-DPPW3TCM0K
ga_domain: 1ping.org

# Baidu Analytics
ba_track_id:

# picture of about page
about_pic: avatar.webp

image_zoom:
  enable: true
